spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=urban_micro_farm_app
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.properties.hibernate.default_schema=urban_micro_farm_app

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.schema=DEBUG
logging.level.org.hibernate.tool.schema=DEBUG