spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=urban_micro_farm_app
spring.datasource.username=postgres
spring.datasource.password=Via@12345

spring.jpa.properties.hibernate.default_schema=${APP_SCHEMA:urban_micro_farm_app}

# JWT
jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXNlY3VyZS0yNTYtYml0LWRlZi1rZXk=}
jwt.expiration=${JWT_EXPIRATION_MS:86400000}

# Jackson
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jackson.default-property-inclusion=non_null

# MQTT
# Automatically run SQL initialization scripts (ensure schema exists before Hibernate starts)
spring.sql.init.mode=always

# For local development: let Hibernate create/update missing tables based on entities
# WARNING: don't use in production without understanding consequences
spring.jpa.hibernate.ddl-auto=update

mqtt.broker=tcp://20.240.208.122:1883
mqtt.client-id=iot-test-client
mqtt.topic=farm/#

# ML
ml.prediction.url=https://waterthingy-hwg6h4gzevedfjc3.germanywestcentral-01.azurewebsites.net/api/predict-watering?code=ViXHI-UoUHEaMvxx9XCNu8gd3TtWe1VGbo-AkbFy2fkHAzFuANQb8Q==