spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.properties.hibernate.default_schema=urban_micro_farm_app
spring.jpa.hibernate.ddl-auto=update